---
title: "STAT 333 - Final Project"
author: "Shivani Potnuru"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## scraping from each billboard top 100 wikipedia page (years 1970 - 2024)

```{r}
library(rvest)
library(tidyverse)
library(purrr)
```

```{r} 
scrape_year <- function(year) {
  url <- paste0("https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_", year)
  page <- read_html(url)
  
  table_node <- page %>% html_node("table.wikitable")
  
  # if no table found; return NULL
  if (is.null(table_node)) {
    warning(paste("No table found for", year))
    return(NULL)
  }
  df <- table_node %>% html_table(fill = TRUE)
  
    if (ncol(df) > 0) {
    names(df)[1] <- "No."
    }
  
  df$Year <- year
  return(df)
}

years <- 1970:2024

all_data <- map_dfr(years, function(y) {
  message("Scraping ", y, "...")
  scraped <- tryCatch(scrape_year(y), error = function(e) NULL)
  scraped
})
```

## organizing to arrange by year

```{r} 
## organizing to arrange by year
if ("№" %in% colnames(all_data)) {
  all_data <- all_data %>% rename(No. = `№`)
}

if ("Artist(s)" %in% colnames(all_data)) {
  all_data <- all_data %>% rename(Artist = `Artist(s)`)
}

# Ensure correct data type
all_data <- all_data %>% mutate(`No.` = as.integer(`No.`))

sep_rx2 <- regex(
  "(?i)\\s*(?:,|&|\\bfeaturing\\b|\\bfeat\\.?\\b|\\bwith\\b|\\bvs?\\.?\\b| and (?!the\\b)| x )\\s*"
)

# Preserve original artist string
rank_by_year <- all_data %>%
  mutate(
    Artist      = tolower(Artist) %>% str_trim(),
    all_artists = Artist,
    artist_list = str_split(Artist, sep_rx2)
  ) %>%
  mutate(
    primary_artist = map_chr(artist_list, 1) %>% str_squish(),
    other_artists  = map_chr(
      artist_list,
      ~ {
        tmp <- discard(.x[-1], ~ .x == "")
        if (length(tmp)==0) return(NA_character_)
        paste(tmp, collapse = ", ")
      }
    )
  ) %>%
  group_by(primary_artist) %>%
  mutate(
    primary_artist_count = n(),
    one_hit              = ifelse(n()==1, 1, 0)
  ) %>%
  ungroup()

# final data w/ selected cols 
final_data <- rank_by_year %>%
  select(
    No., Title, Year,
    Artist,          
    artist_list,      
    primary_artist,
    primary_artist_count,
    one_hit
  )
final_data
```

## connecting to spotify API 

```{r} 
install.packages("spotifyr", repos = "https://cloud.r-project.org/")
library(spotifyr)
library(tidyverse)

Sys.setenv(SPOTIFY_CLIENT_ID = "edfc5777be46422194dcc97219686335")
Sys.setenv(SPOTIFY_CLIENT_SECRET = "a80a0128279e4448bc406d3810795a82")

access_token <- get_spotify_access_token()

```

```{r}
library(jsonlite)
final_data_to_csv <- final_data %>%
  mutate(
    artist_list   = map_chr(artist_list, ~ toJSON(.x, auto_unbox = TRUE)),
  )
readr::write_csv(final_data_to_csv, "STAT333data.csv")
```



























